'use client';
import { useEffect, useState } from 'react';

type Note = { id: string; title: string; content: string; updatedAt: string };

export default function Notes() {
  const [notes,setNotes]=useState<Note[]>([]); const [title,setTitle]=useState(''); const [content,setContent]=useState(''); const [selected,setSelected]=useState<string|null>(null); const [msg,setMsg]=useState('');
  useEffect(()=>{fetch('/api/notes').then(r=>r.ok?r.json():[]).then(setNotes)},[]);
  async function save(){if(!title.trim()||!content.trim()){setMsg('Enter a title and some notes.');return}const method=selected?'PUT':'POST';const body=selected?{id:selected,title,content}:{title,content};const r=await fetch('/api/notes',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setMsg(d.error||'Unable to save note.');return}setNotes(n=>selected?n.map(x=>x.id===d.id?d:x):[d,...n]);setSelected(d.id);setTitle(d.title);setContent(d.content);setMsg('Saved ✓')}
  async function remove(){if(!selected)return;const r=await fetch(`/api/notes?id=${selected}`,{method:'DELETE'});if(r.ok){setNotes(n=>n.filter(x=>x.id!==selected));setSelected(null);setTitle('');setContent('');setMsg('Deleted.')}}
  function download(){const blob=new Blob([`${title}\n\n${content}`],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${(title||'note').replace(/[^a-z0-9]+/gi,'-')}.txt`;a.click();URL.revokeObjectURL(a.href)}
  function newNote(){setSelected(null);setTitle('');setContent('');setMsg('')}
  return <main className="container"><nav className="nav"><b className="brand">INTERVIEW</b><div className="navlinks"><a href="/dashboard">Dashboard</a><a href="/learn">Learning</a><a className="btn" href="/certificates">Certificates</a></div></nav><div className="topline" style={{marginTop:35}}><div><div className="eyebrow">Personal workspace</div><h1 className="title">My Notes</h1><p className="muted">Save interview tips, formulas, code snippets, revision points and anything you want to remember.</p></div><button className="btn" onClick={newNote}>+ New note</button></div><div className="grid" style={{gridTemplateColumns:'280px minmax(0,1fr)'}}><div className="card"><h2>Saved notes</h2>{notes.length===0&&<p className="muted">No notes yet.</p>}{notes.map(n=><button key={n.id} onClick={()=>{setSelected(n.id);setTitle(n.title);setContent(n.content);setMsg('')}} style={{display:'block',width:'100%',textAlign:'left',padding:12,marginTop:8,border:'1px solid #d9dee7',borderRadius:10,background:n.id===selected?'#f2f5f9':'white'}}><b>{n.title}</b><br/><span className="muted">{new Date(n.updatedAt).toLocaleDateString()}</span></button>)}</div><div className="card"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Note title" style={{fontSize:22,fontWeight:700,width:'100%',padding:10,border:'1px solid #ccd3dd',borderRadius:10}}/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Write anything here…" style={{width:'100%',minHeight:420,padding:15,border:'1px solid #ccd3dd',borderRadius:12,marginTop:12}}/><div className="actions" style={{marginTop:12}}><button className="btn" onClick={save}>Save note</button><button className="btn secondary" onClick={download} disabled={!content.trim()}>Download note</button>{selected&&<button className="btn secondary" onClick={remove}>Delete</button>}</div>{msg&&<div className="toast">{msg}</div>}</div></div></main>
}
