'use client';
import { useEffect, useState } from 'react';

type Q={id:string;type:string;topic:string;difficulty:string;question:string;options?:string[];answer?:string;explanation?:string;prompt?:string;expectedConcept?:string};

export default function Practice(){
 const [type,setType]=useState<'aptitude'|'technical'|'coding'|'round1'>('aptitude');
 const [round,setRound]=useState(1); const [topic,setTopic]=useState(''); const [topics,setTopics]=useState<string[]>([]); const [qs,setQs]=useState<Q[]>([]); const [answers,setAnswers]=useState<Record<string,string>>({}); const [submitted,setSubmitted]=useState(false); const [loading,setLoading]=useState(true); const [msg,setMsg]=useState('');
 async function load(nextType=type,nextTopic=topic,nextRound=round){setLoading(true);setSubmitted(false);setAnswers({});setMsg('');const r=await fetch(`/api/practice/questions?type=${encodeURIComponent(nextType)}&topic=${encodeURIComponent(nextTopic)}&round=${nextRound}`);const d=await r.json();if(r.ok){setQs(d.questions||[]);if(d.topics?.length)setTopics(d.topics);if(!nextTopic&&d.topics?.length)setTopic(d.topics[0]);}else setMsg(d.error||'Unable to load practice questions.');setLoading(false)}
 useEffect(()=>{load();},[type]);
 useEffect(()=>{if(topic)load(type,topic,round);},[topic]);
 function submit(){setSubmitted(true);fetch('/api/practice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,topic:topic||`${type}-general`,score:qs.filter(q=>q.answer&&answers[q.id]===q.answer).length,total:qs.length})});}
 const score=qs.filter(q=>q.answer&&answers[q.id]===q.answer).length;
 return <main className="container"><nav className="nav"><b className="brand">INTERVIEW</b><div className="navlinks"><a href="/dashboard">Dashboard</a><a href="/learn">Learning</a></div></nav><div className="topline" style={{marginTop:35}}><div><div className="eyebrow">Practice Lab • 1200+ interview questions</div><h1 className="title">Practice by sub-topic</h1><p className="muted">Questions are selected for your engineering program and learning sub-topics. Aptitude, Technical, Coding and Round 1 practice are separated.</p></div></div><div className="actions" style={{marginBottom:16,flexWrap:'wrap'}}>{(['aptitude','technical','coding','round1'] as const).map(t=><button className={`btn ${type===t?'':'secondary'}`} key={t} onClick={()=>{setType(t);setRound(1);setTopic('')}}>{t==='round1'?'ROUND 1':t[0].toUpperCase()+t.slice(1)}</button>)}<span className="pill">ROUND {round}</span></div><div className="card" style={{marginBottom:18}}><label className="muted"><b>Choose sub-topic</b></label><select value={topic} onChange={e=>setTopic(e.target.value)} style={{display:'block',width:'100%',padding:12,border:'1px solid #ccd3dd',borderRadius:10,marginTop:8}}>{topics.map(t=><option key={t}>{t}</option>)}</select><div className="actions" style={{marginTop:12}}><button className="btn secondary" onClick={()=>{const r=round+1;setRound(r);load(type,topic,r)}}>New 15-question round</button><span className="muted">Large bank: 300 Aptitude + 300 Technical + 300 Coding + 300 Round 1.</span></div></div>{loading?<div className="empty">Loading questions…</div>:<div className="card">{qs.map((q,i)=><div key={q.id} style={{marginBottom:28}}><div className="eyebrow">{i+1} • {q.topic} • {q.difficulty}</div><h3>{q.question}</h3>{q.type==='coding'?<><div className="notice"><b>Challenge</b><p>{q.prompt}</p><p className="muted">{q.expectedConcept}</p></div><textarea value={answers[q.id]||''} onChange={e=>setAnswers(a=>({...a,[q.id]:e.target.value}))} placeholder="Write your approach / solution…" style={{width:'100%',minHeight:150,padding:12,border:'1px solid #ccd3dd',borderRadius:10,fontFamily:'monospace'}}/></>:q.options?.map(o=><label className="quiz-option" key={o}><input type="radio" name={q.id} checked={answers[q.id]===o} onChange={()=>setAnswers(a=>({...a,[q.id]:o}))}/> {o}</label>)}{submitted&&q.answer&&<div className="notice" style={{marginTop:10}}><b>{answers[q.id]===q.answer?'✓ Correct':'✗ Incorrect'}</b><p><b>Correct answer:</b> {q.answer}</p><p className="muted">{q.explanation}</p></div>}{submitted&&q.type==='round1'&&<div className="notice" style={{marginTop:10}}><b>AI interview tip</b><p className="muted">{q.explanation}</p></div>}</div>)}<div className="actions"><button className="btn" onClick={submit}>Submit & Show Correct Answers</button>{submitted&&<span className="pill">Score {score}/{qs.filter(q=>q.answer).length || qs.length}</span>}</div>{msg&&<div className="toast danger">{msg}</div>}</div>}</main>
}
