'use client';
import { useEffect, useState } from 'react';
import { INTERVIEW_COUNT, getQuestions } from '@/lib/interview-questions';

type Q = { question:string; category:string; followUps:string[] };
export default function MockInterview(){
 const [role,setRole]=useState('Software Developer'); const [index,setIndex]=useState(0); const [answer,setAnswer]=useState(''); const [listening,setListening]=useState(false); const [result,setResult]=useState<any>(null); const [msg,setMsg]=useState(''); const [ai,setAi]=useState<Q|null>(null); const [loading,setLoading]=useState(false); const bank=getQuestions(role); const current=ai||bank[index%bank.length];
 useEffect(()=>{const Speech=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Speech)return;const rec=new Speech();rec.continuous=true;rec.interimResults=false;rec.lang='en-US';rec.onresult=(e:any)=>{let text='';for(let i=e.resultIndex;i<e.results.length;i++)text+=e.results[i][0].transcript+' ';setAnswer(a=>a+text)};rec.onend=()=>setListening(false);(window as any).__interviewRec=rec;return()=>{try{rec.stop()}catch{}}},[]);
 function toggleVoice(){const rec=(window as any).__interviewRec;if(!rec){setMsg('Voice recognition is not supported in this browser. Type your answer instead.');return}if(listening){rec.stop();setListening(false)}else{rec.start();setListening(true);setMsg('Listening… speak naturally.')}}
 async function finish(){if(answer.trim().length<10){setMsg('Give a longer answer before scoring.');return}const r=await fetch('/api/mock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role,mode:'voice',transcript:answer})});const d=await r.json();if(r.ok){setResult(d);setMsg('Answer evaluated and saved ✓')}else setMsg(d.error||'Unable to save answer.')}
 function next(){setIndex(i=>i+1);setAi(null);setAnswer('');setResult(null);setMsg('')}
 async function askAI(){setLoading(true);setMsg('AI is preparing a realistic follow-up question…');try{const r=await fetch('/api/ai/interview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role,previousQuestion:current.question,previousAnswer:answer})});const d=await r.json();if(r.ok){setAi(d);setAnswer('');setResult(null);setMsg(d.source==='ai'?'New AI-generated question ready ✓':'New real-world question ready ✓')}else setMsg(d.error||'AI question unavailable.')}finally{setLoading(false)}}
 return <main className="container"><nav className="nav"><b className="brand">INTERVIEW</b><div className="navlinks"><a href="/dashboard">Dashboard</a><a href="/practice">Practice</a></div></nav><div className="card" style={{maxWidth:900,margin:'40px auto'}}><div className="eyebrow">AI mock interview • {INTERVIEW_COUNT}+ real-world questions</div><h1 className="title">{role} interview</h1><label className="muted">Target role</label><select value={role} onChange={e=>{setRole(e.target.value);setIndex(0);setAi(null);setAnswer('');setResult(null)}} style={{width:'100%',padding:12,border:'1px solid #ccd3dd',borderRadius:10,margin:'8px 0 25px'}}><option>Software Developer</option><option>Frontend Developer</option><option>Backend Developer</option><option>Data Analyst</option><option>Java Developer</option><option>AI/ML Engineer</option><option>DevOps Engineer</option><option>Cyber Security Analyst</option></select><div className="topline"><span className="pill">QUESTION {index+1} • {current.category}</span><button className="btn secondary" onClick={askAI} disabled={loading}>{loading?'AI thinking…':'✨ Ask separate AI interviewer'}</button></div><h2>{current.question}</h2>{current.followUps?.length>0&&<div className="notice"><b>Possible follow-ups</b><p className="muted">{current.followUps.join(' • ')}</p></div>}<textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Speak with the microphone or type your answer…" style={{width:'100%',minHeight:190,padding:15,border:'1px solid #ccd3dd',borderRadius:12,marginTop:12}}/><div className="actions" style={{marginTop:14}}><button className="btn" onClick={toggleVoice}>{listening?'Stop listening':'🎙 Start voice answer'}</button><button className="btn secondary" onClick={next}>Next question</button><button className="btn" onClick={finish}>Score answer</button></div>{msg&&<div className="toast">{msg}</div>}{result&&<div className="notice"><div className="score-ring">{result.score}/100</div><b>AI Coach feedback</b><p className="muted">{result.feedback}</p></div>}</div></main>}
