'use client';
import { useEffect, useState } from 'react';
import { COURSES } from '@/lib/courses';

type Cert={id:string;department:string;course:string;certificateNo:string;issuedAt:string};

export default function Certificates(){
  const [certs,setCerts]=useState<Cert[]>([]); const [department,setDepartment]=useState('CSE'); const [name,setName]=useState(''); const [msg,setMsg]=useState('');
  useEffect(()=>{fetch('/api/certificates').then(r=>r.ok?r.json():[]).then(setCerts);fetch('/api/dashboard').then(r=>r.ok?r.json():null).then(d=>setName(d?.user?.name||'Student'))},[]);
  async function generate(){setMsg('Checking course completion…');const r=await fetch('/api/certificates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({department})});const d=await r.json();if(!r.ok){setMsg(d.error||'Complete the course first.');return}setCerts(c=>c.some(x=>x.id===d.id)?c:[d,...c]);setMsg('Certificate generated ✓');}
  async function download(cert:Cert){const {jsPDF}=await import('jspdf');const pdf=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});pdf.setLineWidth(2);pdf.rect(12,12,273,183);pdf.setLineWidth(.5);pdf.rect(18,18,261,171);pdf.setFont('helvetica','bold');pdf.setFontSize(30);pdf.text('CERTIFICATE OF COMPLETION',148,55,{align:'center'});pdf.setFont('helvetica','normal');pdf.setFontSize(16);pdf.text('This certifies that',148,78,{align:'center'});pdf.setFont('helvetica','bold');pdf.setFontSize(25);pdf.text(name||'Student',148,94,{align:'center'});pdf.setFont('helvetica','normal');pdf.setFontSize(15);pdf.text('has successfully completed the 100% learning and practical assessment for',148,110,{align:'center',maxWidth:235});pdf.setFont('helvetica','bold');pdf.setFontSize(19);pdf.text(cert.course,148,128,{align:'center',maxWidth:240});pdf.setFont('helvetica','normal');pdf.setFontSize(12);pdf.text(`Department: ${cert.department}    Certificate No: ${cert.certificateNo}`,148,148,{align:'center'});pdf.text(`Issued: ${new Date(cert.issuedAt).toLocaleDateString()}`,148,158,{align:'center'});pdf.setFontSize(11);pdf.text('INTERVIEW • AI Learning & Interview Training Platform',148,178,{align:'center'});pdf.save(`${cert.certificateNo}.pdf`);}
  return <main className="container"><nav className="nav"><b className="brand">INTERVIEW</b><div className="navlinks"><a href="/dashboard">Dashboard</a><a href="/learn">Learning</a><a href="/notes">My Notes</a></div></nav><div className="topline" style={{marginTop:35}}><div><div className="eyebrow">Achievements</div><h1 className="title">Certificates</h1><p className="muted">Certificates unlock only after every module in a course reaches 100%.</p></div></div><div className="card" style={{marginBottom:18}}><h2>Generate certificate</h2><label className="muted">Course</label><select value={department} onChange={e=>setDepartment(e.target.value)} style={{display:'block',width:'100%',padding:12,border:'1px solid #ccd3dd',borderRadius:10,margin:'8px 0 14px'}}>{COURSES.map(c=><option key={c.department} value={c.department}>{c.department} — {c.title}</option>)}</select><button className="btn" onClick={generate}>Check & Generate Certificate</button>{msg&&<div className="toast">{msg}</div>}</div><div className="grid">{certs.map(c=><div className="card" key={c.id}><span className="pill">CERTIFIED</span><h2>{c.course}</h2><p className="muted">{c.department} • {c.certificateNo}</p><p className="muted">Issued {new Date(c.issuedAt).toLocaleDateString()}</p><button className="btn" onClick={()=>download(c)}>Download PDF</button></div>)}</div></main>
}
