export type InterviewQuestion = { id: number; role: string; category: string; question: string; followUps: string[] };

const base: Array<[string,string,string,string[]]> = [
['Software Developer','Behavioral','Tell me about yourself and the kind of software problems you enjoy solving.',['What project are you most proud of?','What did you personally contribute?']],
['Software Developer','Project','Describe a production bug that was difficult to diagnose.',['How did you reproduce it?','How did you prevent it from returning?']],
['Software Developer','System Design','Design a URL shortening service for millions of users.',['How would you scale reads?','How would you avoid duplicate short URLs?']],
['Software Developer','System Design','Design a notification system that supports email, SMS and push notifications.',['How would you retry failures?','How would you make delivery idempotent?']],
['Software Developer','Coding','How would you find the first non-repeating character in a string?',['What is your time complexity?','Can you reduce extra memory?']],
['Software Developer','Debugging','A service suddenly has high CPU after a deployment. What would you investigate first?',['Which metrics would you inspect?','How would you roll back safely?']],
['Software Developer','Database','When would you add a database index and what trade-offs does it introduce?',['How do you verify an index helps?','What happens to writes?']],
['Software Developer','Security','How would you protect an API from brute-force login attempts?',['Where would rate limiting live?','How would you handle distributed clients?']],
['Software Developer','Architecture','When would you choose a monolith over microservices?',['What migration signal would make you split a service?','What operational cost does microservices add?']],
['Software Developer','Testing','How would you test a payment flow where an external gateway can time out?',['How do you test retries?','How do you prevent double charging?']],
['Frontend Developer','Frontend','A React page becomes slow as a list grows to 10,000 items. How would you improve it?',['Would you virtualize the list?','How would you measure the improvement?']],
['Frontend Developer','Frontend','Explain how you would debug a layout that works on desktop but breaks on mobile.',['Which browser tools would you use?','How would you prevent regressions?']],
['Frontend Developer','Frontend','How would you design accessible form validation?',['How should errors be announced?','What keyboard behavior matters?']],
['Frontend Developer','Performance','A web page has a poor Largest Contentful Paint. What would you investigate?',['How do images affect LCP?','Which measurements would you compare before and after?']],
['Frontend Developer','Security','How would you protect a browser application against XSS?',['Where should untrusted HTML be sanitized?','Why is CSP useful?']],
['Backend Developer','Backend','An API endpoint becomes slow only during peak traffic. How would you diagnose it?',['How would you distinguish DB and application bottlenecks?','When would caching help?']],
['Backend Developer','API','Design an API for uploading large files reliably.',['How would resumable uploads work?','How would you validate file type and size?']],
['Backend Developer','Distributed Systems','What does idempotency mean for an API and why is it important for retries?',['Give a payment example.','How would you store idempotency keys?']],
['Backend Developer','Database','A query is correct but takes 8 seconds. Walk through your optimization process.',['Would you inspect the query plan?','What can cause a missing index to hurt?']],
['Backend Developer','Reliability','How would you make a backend service survive a downstream service outage?',['Explain timeouts and circuit breakers.','How would you degrade gracefully?']],
['Java Developer','Java','Explain the difference between an interface and an abstract class with a real application example.',['When would you choose each?','How does composition compare?']],
['Java Developer','Java','A Java application has increasing memory usage. How would you investigate a possible memory leak?',['Which JVM tools help?','What heap evidence would you inspect?']],
['Java Developer','Concurrency','Explain a race condition and how you would prevent it in Java.',['When is synchronized appropriate?','What alternatives exist?']],
['Java Developer','Spring','How would you design a Spring Boot REST API with validation and global error handling?',['Where would validation occur?','How would errors be structured?']],
['Java Developer','Database','How would you handle a transaction that updates multiple related tables?',['What isolation level might matter?','What happens after a rollback?']],
['Data Analyst','Analytics','A business metric suddenly drops 20%. How would you investigate before presenting a conclusion?',['What segments would you check?','How would you distinguish data quality from real change?']],
['Data Analyst','SQL','Write the approach for finding the top three products by revenue in each region.',['Which window function helps?','How would you handle ties?']],
['Data Analyst','Statistics','Explain correlation versus causation using a business example.',['What confounder could exist?','How could an experiment help?']],
['Data Analyst','Visualization','How would you choose a chart for monthly sales across several product categories?',['When is a line chart appropriate?','How would you avoid misleading scales?']],
['Data Analyst','Business','A manager asks for a dashboard with 30 metrics. How would you decide what belongs on the first version?',['How would you define success?','How would you collect stakeholder requirements?']],
['AI/ML Engineer','Machine Learning','A model has 98% training accuracy but 72% validation accuracy. What does this suggest and what would you try?',['How could regularization help?','What would you check in the data split?']],
['AI/ML Engineer','Machine Learning','How would you detect data leakage before deploying a model?',['Give a feature example.','Why can leakage make validation misleading?']],
['AI/ML Engineer','MLOps','Design a pipeline for retraining a model when fresh labeled data arrives.',['How would you version data and models?','What would trigger rollback?']],
['AI/ML Engineer','NLP','How would you evaluate a customer-support classifier when some classes are rare?',['Why can accuracy be misleading?','Which metrics would you report?']],
['AI/ML Engineer','Production','A deployed model's accuracy gradually declines. What possible causes would you investigate?',['What is data drift?','How would monitoring detect it?']],
['DevOps Engineer','DevOps','A deployment succeeds but the application returns 500 errors. What is your incident workflow?',['What logs and health checks matter?','When would you roll back?']],
['DevOps Engineer','Cloud','How would you design a highly available web application across multiple availability zones?',['What happens if one zone fails?','Where would state live?']],
['DevOps Engineer','CI/CD','What quality gates would you put before production deployment?',['Which tests should block release?','How would you handle emergency fixes?']],
['DevOps Engineer','Containers','Why might a Docker container work locally but fail in production?',['What environment differences matter?','How would you debug it?']],
['DevOps Engineer','Observability','What should a production service monitor besides CPU and memory?',['Which application-level metrics matter?','How do logs, metrics and traces complement each other?']],
['Cyber Security Analyst','Security','A user reports a suspicious login alert. Walk through your investigation.',['What evidence would you collect?','How would you contain the account safely?']],
['Cyber Security Analyst','Security','How would you explain least privilege to a development team?',['Give an API example.','How should privileges be reviewed?']],
['Cyber Security Analyst','Web Security','Explain how SQL injection happens and how a modern application prevents it.',['Why are parameterized queries effective?','What else belongs in defense in depth?']],
['Cyber Security Analyst','Incident Response','How would you prioritize several security alerts arriving at once?',['What makes an alert high severity?','How would you reduce false positives?']],
['Cyber Security Analyst','Identity','How would you design secure authentication for a student web platform?',['Why use short-lived sessions?','How should passwords be stored?']],
];

export const INTERVIEW_QUESTIONS: InterviewQuestion[] = Array.from({length: 3}, (_,round) => base.map((x,i) => ({id: round*base.length+i+1, role:x[0], category:x[1], question: round===0?x[2]: `${x[2]} Imagine this is happening in a real production team today. What would you do first, and why?`, followUps:x[3]}))).flat();
export const INTERVIEW_COUNT = INTERVIEW_QUESTIONS.length;
export function getQuestions(role:string){const exact=INTERVIEW_QUESTIONS.filter(q=>q.role===role);return exact.length?exact:INTERVIEW_QUESTIONS;}
