export type LearningProblem = {
  id: string;
  title: string;
  level: 'Easy' | 'Medium' | 'Hard';
  problem: string;
  input: string;
  output: string;
  constraints: string;
  example: string;
  timeLimit: string;
  memoryLimit: string;
};

type RawProblem = Omit<LearningProblem, 'id'>;

const BANK: RawProblem[] = [
  { title: 'Array Frequency', level: 'Easy', problem: 'Given N integers, find the value that occurs most often. If multiple values have the same maximum frequency, print the smallest value. This problem tests counting, maps and careful tie handling.', input: 'The first line contains N. The second line contains N integers.', output: 'Print the smallest value having maximum frequency followed by its frequency.', constraints: '1 <= N <= 2*10^5; -10^9 <= A[i] <= 10^9', example: 'Input:\n7\n4 2 4 3 2 4 3\nOutput:\n4 3', timeLimit: '1 second', memoryLimit: '256 MB' },
  { title: 'Maximum Subarray', level: 'Medium', problem: 'Find the maximum possible sum of a non-empty contiguous subarray. The array may contain negative values.', input: 'The first line contains N. The second line contains N integers.', output: 'Print the maximum subarray sum.', constraints: '1 <= N <= 2*10^5; -10^9 <= A[i] <= 10^9', example: 'Input:\n6\n-2 3 2 -1 4 -5\nOutput:\n8', timeLimit: '1 second', memoryLimit: '256 MB' },
  { title: 'Two Sum Positions', level: 'Easy', problem: 'Given an array and target X, find two different zero-based positions whose values sum to X. Print the lexicographically smallest pair, or -1 if no pair exists.', input: 'The first line contains N and X. The second line contains N integers.', output: 'Print two zero-based indices or -1.', constraints: '2 <= N <= 2*10^5; |A[i]|, |X| <= 10^9', example: 'Input:\n5 10\n3 7 4 6 8\nOutput:\n0 1', timeLimit: '1 second', memoryLimit: '256 MB' },
  { title: 'Rotate and Query', level: 'Medium', problem: 'An array is circularly rotated to the right by K positions. After rotation, answer Q index queries. Do not build another array unless necessary.', input: 'First line N K Q. Second line contains N integers. Next Q lines contain an index.', output: 'For every query print the value at that index after rotation.', constraints: '1 <= N,Q <= 2*10^5; 0 <= K <= 10^9', example: 'Input:\n5 2 3\n10 20 30 40 50\n0\n2\n4\nOutput:\n40\n10\n30', timeLimit: '1 second', memoryLimit: '256 MB' },
  { title: 'Longest Unique Substring', level: 'Medium', problem: 'Given a string, find the length of the longest contiguous substring containing no repeated character.', input: 'One line containing a string S.', output: 'Print the maximum length.', constraints: '1 <= |S| <= 2*10^5; S contains ASCII characters.', example: 'Input:\nabcaabcd\nOutput:\n4', timeLimit: '1 second', memoryLimit: '256 MB' },
  { title: 'Balanced Brackets', level: 'Easy', problem: 'For each test case, determine whether a string containing (), {}, and [] is balanced. Brackets must close in the correct order.', input: 'First line T. Each following line contains one bracket string.', output: 'Print YES or NO for each test case.', constraints: '1 <= T <= 10^4; total length <= 2*10^5', example: 'Input:\n3\n{[()]}\n([)]\n()[]{}\nOutput:\nYES\nNO\nYES', timeLimit: '1 second', memoryLimit: '256 MB' },
  { title: 'Next Greater Element', level: 'Medium', problem: 'For every element of an array, find the first element to its right that is strictly greater. Print -1 when it does not exist.', input: 'The first line contains N. The second line contains N integers.', output: 'Print N answers separated by spaces.', constraints: '1 <= N <= 2*10^5; -10^9 <= A[i] <= 10^9', example: 'Input:\n5\n4 5 2 10 8\nOutput:\n5 10 10 -1 -1', timeLimit: '1 second', memoryLimit: '256 MB' },
  { title: 'Shortest Path in a Grid', level: 'Hard', problem: 'A grid contains 0 for an open cell and 1 for a blocked cell. Starting at the top-left, find the minimum number of moves needed to reach the bottom-right using four-directional moves.', input: 'First line H W. Next H lines contain W binary values.', output: 'Print the shortest distance, or -1 when unreachable.', constraints: '1 <= H,W <= 500', example: 'Input:\n3 4\n0 0 1 0\n0 0 0 0\n1 0 0 0\nOutput:\n5', timeLimit: '2 seconds', memoryLimit: '256 MB' },
  { title: 'Connected Components', level: 'Medium', problem: 'Given an undirected graph, count how many connected components it contains.', input: 'First line N M. Next M lines contain edges u v using 1-based vertices.', output: 'Print the number of connected components.', constraints: '1 <= N <= 2*10^5; 0 <= M <= 2*10^5', example: 'Input:\n5 3\n1 2\n2 3\n4 5\nOutput:\n2', timeLimit: '1 second', memoryLimit: '256 MB' },
  { title: 'Shortest Job First', level: 'Medium', problem: 'Given N jobs with arrival and burst times, calculate the average waiting time when jobs are always selected by the shortest available burst time. Break ties by smaller job id.', input: 'First line N. Next N lines contain arrival time and burst time.', output: 'Print the average waiting time rounded to two decimal places.', constraints: '1 <= N <= 10^5; 0 <= arrival,burst <= 10^6', example: 'Input:\n3\n0 5\n1 2\n2 1\nOutput:\n2.33', timeLimit: '2 seconds', memoryLimit: '256 MB' },
  { title: 'Matrix Prefix Queries', level: 'Medium', problem: 'Build a two-dimensional prefix sum and answer rectangular sum queries quickly.', input: 'First line N M. Next N lines contain the matrix. Then Q and Q rectangles r1 c1 r2 c2 using 1-based inclusive coordinates.', output: 'Print one sum per query.', constraints: '1 <= N,M <= 1000; 1 <= Q <= 2*10^5', example: 'Input:\n2 3\n1 2 3\n4 5 6\n2\n1 1 1 2\n1 2 2 3\nOutput:\n3\n16', timeLimit: '2 seconds', memoryLimit: '256 MB' },
  { title: 'Coin Change Minimum', level: 'Hard', problem: 'Given coin denominations and a target value, find the minimum number of coins needed to make exactly the target. Each denomination can be used unlimited times.', input: 'First line N X. Second line contains N positive denominations.', output: 'Print the minimum number of coins, or -1 if the target cannot be formed.', constraints: '1 <= N <= 100; 1 <= X <= 10^5', example: 'Input:\n3 11\n1 5 7\nOutput:\n3', timeLimit: '2 seconds', memoryLimit: '256 MB' },
  { title: 'Longest Increasing Subsequence', level: 'Hard', problem: 'Find the length of the longest strictly increasing subsequence of an integer array.', input: 'The first line contains N. The second line contains N integers.', output: 'Print the LIS length.', constraints: '1 <= N <= 2*10^5; |A[i]| <= 10^9', example: 'Input:\n8\n10 9 2 5 3 7 101 18\nOutput:\n4', timeLimit: '2 seconds', memoryLimit: '256 MB' },
  { title: 'SQL-Style Record Aggregation', level: 'Medium', problem: 'You receive records containing a category and a value. Aggregate the total value for every category and print categories in lexicographic order. Treat category names case-sensitively.', input: 'First line N. Next N lines contain a category string and an integer value.', output: 'Print category and total on one line for each distinct category.', constraints: '1 <= N <= 2*10^5; category length <= 50', example: 'Input:\n4\nA 10\nB 5\nA 7\nC 3\nOutput:\nA 17\nB 5\nC 3', timeLimit: '1 second', memoryLimit: '256 MB' },
  { title: 'Binary Search Queries', level: 'Easy', problem: 'The array is sorted in non-decreasing order. For each query, print the first position containing the target value, or -1.', input: 'First line N Q. Second line contains N sorted integers. Next Q lines contain a target.', output: 'Print one zero-based position per query.', constraints: '1 <= N,Q <= 2*10^5', example: 'Input:\n6 4\n1 2 2 2 5 9\n2\n5\n3\n1\nOutput:\n1\n4\n-1\n0', timeLimit: '1 second', memoryLimit: '256 MB' },
  { title: 'Prime Range Queries', level: 'Medium', problem: 'For each query [L,R], report how many prime numbers are in the inclusive range. Preprocess the range so many queries can be answered efficiently.', input: 'First line Q. Next Q lines contain L R.', output: 'Print the number of primes in each range.', constraints: '1 <= Q <= 2*10^5; 1 <= L <= R <= 10^6', example: 'Input:\n3\n1 10\n10 20\n20 30\nOutput:\n4\n4\n2', timeLimit: '2 seconds', memoryLimit: '256 MB' },
  { title: 'Interval Scheduling', level: 'Medium', problem: 'Given intervals representing meetings, select the maximum number of non-overlapping meetings. A meeting ending at time t can be followed by one starting at t.', input: 'First line N. Next N lines contain start and end times.', output: 'Print the maximum number of meetings.', constraints: '1 <= N <= 2*10^5', example: 'Input:\n5\n1 3\n2 4\n3 5\n0 6\n5 7\nOutput:\n3', timeLimit: '1 second', memoryLimit: '256 MB' },
  { title: 'Frequency Window', level: 'Hard', problem: 'Find the smallest length of a contiguous subarray containing at least K distinct values.', input: 'First line N K. Second line contains N integers.', output: 'Print the minimum length, or -1 when impossible.', constraints: '1 <= N <= 2*10^5; 1 <= K <= N', example: 'Input:\n7 3\n1 2 1 3 4 2 3\nOutput:\n3', timeLimit: '1 second', memoryLimit: '256 MB' },
  { title: '0/1 Knapsack', level: 'Hard', problem: 'Choose each item at most once. Maximize total value without exceeding the capacity.', input: 'First line N W. Next N lines contain weight and value.', output: 'Print the maximum value.', constraints: '1 <= N <= 200; 1 <= W <= 10^5', example: 'Input:\n3 7\n3 4\n4 5\n5 7\nOutput:\n9', timeLimit: '2 seconds', memoryLimit: '256 MB' },
  { title: 'String Transformation Cost', level: 'Hard', problem: 'Given two strings, find the minimum number of insertions, deletions and substitutions required to transform the first string into the second.', input: 'First line string A. Second line string B.', output: 'Print the minimum edit distance.', constraints: '1 <= |A|,|B| <= 2000', example: 'Input:\nkitten\nsitting\nOutput:\n3', timeLimit: '2 seconds', memoryLimit: '256 MB' },
  { title: 'Range Minimum Queries', level: 'Hard', problem: 'Given an immutable array, answer many minimum-value queries over inclusive ranges. The solution must be designed for large input.', input: 'First line N Q. Second line N integers. Next Q lines contain L R using zero-based indices.', output: 'Print the minimum for every query.', constraints: '1 <= N,Q <= 2*10^5', example: 'Input:\n5 3\n5 2 7 1 6\n0 2\n1 3\n2 4\nOutput:\n2\n1\n1', timeLimit: '2 seconds', memoryLimit: '256 MB' },
  { title: 'Large Input Simulation', level: 'Hard', problem: 'Process T independent test cases. For each case, maintain a state while reading N operations and print the final state. The input is intentionally large, so buffered I/O and an O(N) or O(N log N) approach are expected.', input: 'First line T. For every case, read N followed by N operation records defined by the task.', output: 'Print one final answer per test case.', constraints: 'Sum of N over all test cases <= 5*10^5', example: 'Input:\n1\n5\nADD 3\nADD 7\nREMOVE 3\nADD 2\nREMOVE 9\nOutput:\n9', timeLimit: '2 seconds', memoryLimit: '256 MB' },
];

export function getLearningProblems(moduleTitle: string): LearningProblem[] {
  const module = moduleTitle.trim();
  return BANK.map((p, index) => ({
    ...p,
    id: `${module.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${index + 1}`,
    title: `${index + 1}. ${p.title}`,
    problem: `${p.problem}\n\nLearning focus: ${module}. Apply the concepts from this module while solving the problem.`,
  }));
}
